language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
- bower install
- sudo pip install pillow
script: grunt travis
addons:
  firefox: '30.0'
env:
  global:
    secure: dB3WMokJn/Z5d5Hpal4i+xtXw/8af7BxCyLL7h2fG4LlDgqke9QDL8t4RL6oEodAoMp1KIwASl2MQqnjgUOO+XzB+WCje9CiA22BIj3Q7CAgjImbPzY6i1ijDZJ8YwfHbdvzqGkZUL/INEmwCcrlsQGKagsHXNQ3n3uejzTnfj0=
after_script:
  - bash test/visual/scripts/send.sh
